import { Text } from "./Text";
import { Heading } from "./Heading";
import { Img } from "./Img";
import { Button } from "./Button";
import { RatingBar } from "./RatingBar";
import { SelectBox } from "./SelectBox";
import { Input } from "./Input";
import { TextArea } from "./TextArea";
import { Radio } from "./Radio";
import { GoogleMap } from "./GoogleMap";
export { Text, Heading, Img, Button, RatingBar, SelectBox, Input, TextArea, Radio, GoogleMap };
